FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json tsconfig.json ./
COPY apps apps
COPY packages packages
RUN npm ci
RUN npm run build -w @subtitle/contracts && npm run build -w @subtitle/api
FROM node:22-alpine
WORKDIR /app
COPY --from=build /app .
CMD ["node","apps/api/dist/server.js"]
