FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json tsconfig.json ./
COPY apps/api/package.json apps/api/package.json
COPY packages/contracts/package.json packages/contracts/package.json
RUN npm install
COPY apps/api apps/api
COPY packages/contracts packages/contracts
RUN npm run build -w @subtitle/contracts && npm run build -w @subtitle/api
FROM node:22-alpine
WORKDIR /app
COPY --from=build /app .
CMD ["node","apps/api/dist/server.js"]
